package com.servicerswitch.engine.findings;

public enum FindingType {
  ESCROW_BALANCE_MISMATCH,
  PROPERTY_TAX_PROJECTION_MISMATCH,
  ESCROW_SHORTAGE_CALCULATION_ERROR,
  DUPLICATE_TAX_DISBURSEMENT,
  UNEXPLAINED_PAYMENT_INCREASE,
  EXPLAINED
}
